### ISSUE TITLE
Blue button color too bright/intense

### ISSUE THREAD

**Issue by deepspaceaxolotl** [KevinPayravi/indie-wiki-buddy-site#1]
The shade of blue of the blue buttons on the site is very intense and, for me at least, is painful. This might be an accessibility issue for other people, too. The background colour is a much nicer shade so maybe the buttons could be changed to that same shade?

**Comment by KevinPayravi** [comment]
Hi @deepspaceaxolotl - thank you for reporting this!

I've changed the button colors to match the background color, let me know if it looks good.
![image](https://user-images.githubusercontent.com/7636606/223962806-af190428-95c4-400c-87c3-24048f36bf47.png)

**Comment by deepspaceaxolotl** [comment]
Looks good to me, thank you!
